name: Kernel CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v2

    - name: Getting Toolchain
      run: |
        sudo apt-get install lib32z1 ccache autoconf
        sudo git clone --depth 1 --branch stable-gcc --single-branch https://github.com/radcolor/arm-linux-gnueabi /opt/toolchains/arm-linux-gnueabi/
    - name: Building Kernel
      run: |
        export KBUILD_BUILD_USER=notnoelchannel
        export KBUILD_BUILD_HOST=unlegacy-devices
        make -j22 ARCH=arm VARIANT_DEFCONFIG=msm8930_loganre_eur_lte_defconfig cyanogen_loganre_defconfig
        make oldconfig
        make -j129
    - name: Moving Output # CI only
      run: |
        mkdir -p /home/runner/work/output
        cp arch/arm/boot/zImage /home/runner/work/output/zImage
    - name: Uploading Output
      uses: actions/upload-artifact@v2
      with:
        name: zImage
        path: /home/runner/work/output/zImage
